version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.fabric8:openshift-client
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.2.0
    - 5.2.1
    - 5.3.0
  - dependency-name: io.vertx:vertx-stack-depchain
    versions:
    - 4.0.0
    - 4.0.1
    - 4.0.2
  - dependency-name: pl.project13.maven:git-commit-id-plugin
    versions:
    - 4.0.3
  - dependency-name: io.reactiverse:vertx-maven-plugin
    versions:
    - 1.0.23
